config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :articles do
    resources :comments, only: [:create, :update]
  end

  resources :projects

  resources :contacts, only: [:create]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validate :name, presence: true
  validate :email, presence: true
  validate :message, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  validates :technologies_used, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, foreign_key: 'author_id'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.email = "#{user.username}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def editor?
    role == 'editor'
  end

  def author?
    role == 'author'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = policy_scope(Article)
  end

  def show
    @comment = @article.comments.build
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    current_user.articles << @article

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, (
                                    :published if current_user.role == 'editor'
                                    ))
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article

  def create
    @comment = @article.comments.build(comment_params)

    if @comment.save
      flash[:notice] = 'Comment created! Approval pending.'
      redirect_to article_path(@article)
    else
      render 'posts/show'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    authorize @comment

    if @comment.update(comment_params)
      flash[:notice] = 'Comment approved!'
      redirect_to article_path(@article)
    else
      render 'posts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(
      :author,
      :author_email,
      :content,
      :approved
      )
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMeEmailJob.new.async.perform(@contact)
      redirect_to root_path, success: 'Your email has been sent!'
    else
      render 'welcome/index', error: 'Looks like you missed a field.'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env['omniauth.auth'])

    if user.persisted?
      flash[:notice] = 'Success! Signed in!'
      sign_in_and_redirect user
    else
      session['devise.user_attributes'] = user.user_attributes
      redirect_to new_user_registration_path
    end
  end

  alias_method :twitter, :all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.js
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.js
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :technologies_used)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  = render 'shared/errors', object: @article
  .actions.row
    .small-6.columns
      = f.label :title
      = f.text_field :title
    .small-8.columns
      = f.label "Content"
      = f.text_area :body, rows: 15
    - if policy(@article).publish?
      .small-3.columns
        = f.label :published, class: 'right-inline', title: 'Is this article published?', data: {tooltip: true}
        = f.check_box :published
  .field
    = f.submit @article.new_record? ? 'Create Article' : 'Update Article', class: "button small radius"

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Blog
- @articles.each do |article|
  .row
    .small-9.columns
      .panel.radius
        %p Title: #{ link_to article.title, article_path(article) }
        - if policy(article).update?
          = link_to 'Edit', edit_article_path(article)
        - if policy(article).destroy?
          \|
          = link_to 'Destroy', article, method: :delete, data: { :confirm => 'Are you sure?' }
%br
- if policy(@articles).create?
  = link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
.row
  .large-12.columns{:role => "content"}
    %h1 Blog
    %br/
    %article
      %h3
        = @article.title
      %h6
        Written by
        = @article.author.email
      .row
        .large-12.columns
          %p= simple_format @article.body
    %hr/
.row
  .large-9.columns
    = link_to 'Edit', edit_article_path(@article)
    \|
    = link_to 'Back', articles_path

    %p.status= "Status: #{@article.published? ? 'Published' : 'Unpublished'}"

    = render 'comments/form'

- policy_scope(@article.comments).each do |comment|
  = button_to 'Approve Comment', article_comment_path(@article, comment, comment: { approved: true }), method: :patch unless comment.approved
  = comment.content
  %p by #{comment.author}

app/views/comments/_form.html.haml
= form_for [@article, @comment] do |f|
  = render 'shared/errors', object: @comment
  .actions.row
    .small-6.columns
      = f.label :author
      = f.text_field :author
    .small-6.columns
      = f.label :author_email
      = f.email_field :author_email
    .small-6.columns
      = f.label :content, rows: 8
      = f.text_area :content
    .small-6.columns
      = f.submit 'Create comment', class: 'btn'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
#header-landing{"data-magellan-destination" => "home"}
  .fixed.sticky
    %nav.top-bar{"data-topbar" => true}
      .top-bar-section
        %ul.title-area
          %li.name
            %h1
              %a{:href => "index.html"}
                %i.fa.fa-bullseye
                = link_to "Reed's Portfolio", root_path
          %li.toggle-topbar.menu-icon
            %a{:href => "#"}
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%ul.right.scroll-nav
  %li.active{"data-magellan-arrival" => "home"}
    =link_to 'Home', root_path
  %li{"data-magellan-arrival" => "services"}
    =link_to 'Blog', articles_path
  %li{"data-magellan-arrival" => "portfolio"}
    =link_to 'Projects', projects_path
  %li{"data-magellan-arrival" => "team"}
    =link_to 'Log In', login_path
    - if user_signed_in?
      %li{"data-magellan-arrival" => "contact"}
        =link_to 'Log out', logout_path
    - else
      %li{"data-magellan-arrival" => "contact"}
        =link_to 'Sign Up', signup_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Portfolio'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Portfolio'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/projects/_form.html.haml
= form_for(@project, remote: true) do |f|
  = render 'shared/errors', object: @project
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :technologies_used
    %br/
    = f.text_area :technologies_used
  .actions
    = f.submit "Save"

= link_to 'Cancel', :back

app/views/projects/_project.html.haml
.row
  .small-9.columns
    .panel.radius
      %h3 Name: #{ link_to project.name, project_path(project) }
      %p= project.technologies_used
      = link_to 'Show', project_path(project)
      \|
      = link_to 'Edit', edit_project_path(project), id: "edit_project_link", remote: true
      \|
      = link_to 'Destroy', project_path(project), method: :delete,
        data: { :confirm => 'Are you sure?' }, remote: true

app/views/projects/create.js.erb
$('#new_project').remove();
$('#new_project_link').show();
$('.container').append('<%= j render(@project) %>');

app/views/projects/destroy.js.erb
$('#project_<%= @project.to_param %>').remove();

app/views/projects/edit.html.haml
%h1 Edit Project

= render 'form'

app/views/projects/index.html.haml
%h1 Projects
.container
  = render @projects
%br

= link_to 'New Project', new_project_path, id: "new_project_link", remote: true

app/views/projects/new.html.haml
%h1 New project

= render 'form'

app/views/projects/show.html.haml
%h1= @project.name
%p= @project.technologies_used

app/views/projects/update.js.erb
$('#edit_project').remove();
$('#edit_project_link').show();
$('<%= j render(@project) %>');

app/views/shared/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this article from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/welcome/index.html.haml
%h2 Welcome to Reed's Page!

%h3 Contact Me
.actions.row
  = form_for @contact do |f|
    = f.label :name
    = f.text_field :name
    = f.label :email
    = f.text_field :email
    = f.label :message
    = f.text_area :message, rows: 8
    = f.submit